# Generated by Django 3.1.3 on 2020-11-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccesRecords',
            new_name='AccessRecords',
        ),
    ]
