# Generated by Django 3.1.3 on 2020-11-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20201112_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='app_user',
            new_name='app_users',
        ),
    ]
